#!/bin/env bash
# Bash script to display information about subdomains
function subinfo {
	if [ -z $2 ] ; then
		
		#domain info
		sub="www.$1"
		rec_type="$(dig $sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')"
		www_ip="$(dig $sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
		echo "The subdomain www is a $rec_type record and points to $www_ip"
		
		# load balance info
		lb1sub="lb-01.$1"
		lb1_rec_type="$(dig $lb1sub | grep -A1 'ANSER SECTION' | tail -1 | awk '{print $4}' )"
		lb_ip="$(dig $lb1sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
		echo "The subdomain lb-01 is a $lb1_rec_type record and points to $lb_ip"
		
		#web-01 server info
		web1_sub="web-01.$1"
		web1_rec_type="$(dig $web1_sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')"
		web1_ip="$(dig $web1_sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
		echo "The subdomain web- is a $web1_rec_type record and points to $web1_ip"
		
		# web-02 servewr info
		web2_sub="web-02.$1"
		web2_rec_type="$(dig $web2_sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')"
		web2_ip="$(dig $web2_sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
		echo "The subdomain web-02 is a $web2_rec_type record and points to $web2_ip"

	elif [ $# -eq 2 ] ; then
		subdomain="$2.$1"
		rec_type="$(dig $subdomain | grep -A1 'ANSER SECTION' | tail -1 | awk '{print $4}')"
		ip="$(dig $subdomain |grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
		echo "The subdoian $2 is a $rec_type record and points to $ip"
	fi
}
subinfo $1 $2

