#!/usr/bin/env bash
# create a script to install and configure HAproxy on ln-01 server
# configure Haproxy to send traffic to web-01 and web-02 servers
#Distrubute requests usingf a roundrobin algorithm
# make sure that HAproxy can be managed via init script
#Inastall and congiure
sudo apt-get update
sudo apt-get -y install haproxy

#edit config file
server_config="
frontend web_front
	bind *:80
	default_backend web_back
backend web_back
	balance roundrobin
	server 104693-web-01 18.204.8.75 check
	server 104693-web-02 107.22.145.89 check"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be statred by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

