#!/usr/bin/env bash
# create a script to install and configure HAproxy on ln-01 server
# configure Haproxy to send traffic to web-01 and web-02 servers
#Distrubute requests usingf a roundrobin algorithm
# make sure that HAproxy can be managed via init script
#Inastall and congiure

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  ben-frontend
        bind *:80
        mode http
        default_backend ben-backend
backend ben-backend
        balance roundrobin
        server 104693-web-01 18.204.8.75:80 check
        server 104693-web-02 107.22.145.89:80 check
"
sudo echo "$server_config" >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart


