#!/usr/bin/env bash
#create file, display text indefinitely, dispolay text on SIGTERM,SIGINT, delete file

rmfile_n_exit()
{
	rm -f /var/run/myscript.pid;
	exit
}
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGTERM
trap "echo 'Y U no love me'" SIGINT
trap "echo 'I hate the kill command'rmfile_n_exit" SIGQUIT

echo $$ >> /var/run/myscript.pid
while true
do
	echo 'To infinity and beyond'
	sleep 2
done
