#!/usr/bin/env bash
# congigure ubuntu server to resolve localhost to 127.0.0.2 facebook.com to 8.8.8.8
#http://blog.jonathanargentiero.com/docker-sed-cannot-rename-etcsedl8ysxl-device-or-resource-busy/
cp etc/hosts hosts_new
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts_new
cp -f hosts_new /etc/hosts
